// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/burari-scene": {
            "post": {
                "description": "endpoint for change OBS scene to burari-travel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scene"
                ],
                "summary": "change to burari scene",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cm-scene": {
            "post": {
                "description": "endpoint for change OBS scene to cm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scene"
                ],
                "summary": "change to cm scene",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversion/cm-mode": {
            "post": {
                "description": "endpoint for conversion to cm-mode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "conversion cm-mode",
                "parameters": [
                    {
                        "description": "post CM request",
                        "name": "CMStateStart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CMStateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversion/start": {
            "post": {
                "description": "endpoint for start conversion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "conversion start",
                "parameters": [
                    {
                        "description": "post conversion request",
                        "name": "conversionStart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.ConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/display-copyright": {
            "post": {
                "description": "endpoint to display copyright",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "display-copyright"
                ],
                "summary": "display copyright",
                "parameters": [
                    {
                        "description": "post display-copyright",
                        "name": "isDisplayedCopy-right",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.DisplayCopyrightRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/force_mute": {
            "post": {
                "description": "endpoint for force mute and prevent changes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "force_mute"
                ],
                "summary": "force mute",
                "parameters": [
                    {
                        "description": "select mute state",
                        "name": "isMuted",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.MuteStateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "endpoint for health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/normal-scene": {
            "post": {
                "description": "endpoint for change OBS scene to normal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scene"
                ],
                "summary": "change to normal scene",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/performance/music": {
            "post": {
                "description": "endpoint for start performance music",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "start performance music",
                "parameters": [
                    {
                        "description": "post performance music",
                        "name": "performanceMusic",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.MusicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/performance/start": {
            "post": {
                "description": "endpoint for start performance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "start performance",
                "parameters": [
                    {
                        "description": "post performance request",
                        "name": "performanceStart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.PerformanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/performances": {
            "get": {
                "description": "endpoint for get performances data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performances"
                ],
                "summary": "get performances data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.PerformancesResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "requests.CMStateRequest": {
            "type": "object",
            "required": [
                "is_cm_mode"
            ],
            "properties": {
                "is_cm_mode": {
                    "description": "binding:\"required\"の影響でfalseを渡したときにエラーが出るので、bool型ではなくポインタを渡す",
                    "type": "boolean"
                }
            }
        },
        "requests.ConversionRequest": {
            "type": "object",
            "required": [
                "next_performances"
            ],
            "properties": {
                "next_performances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.NextPerformanceRequest"
                    }
                }
            }
        },
        "requests.DisplayCopyrightRequest": {
            "type": "object",
            "required": [
                "is_displayed_copyright"
            ],
            "properties": {
                "is_displayed_copyright": {
                    "type": "boolean"
                }
            }
        },
        "requests.MusicRequest": {
            "type": "object",
            "required": [
                "artist",
                "should_be_muted",
                "title"
            ],
            "properties": {
                "artist": {
                    "type": "string"
                },
                "should_be_muted": {
                    "description": "binding:\"required\"の影響でfalseを渡したときにエラーが出るので、bool型ではなくポインタを渡す",
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "requests.MuteStateRequest": {
            "type": "object",
            "required": [
                "is_muted"
            ],
            "properties": {
                "is_muted": {
                    "description": "binding:\"required\"の影響でfalseを渡したときにエラーが出るので、bool型ではなくポインタを渡す",
                    "type": "boolean"
                }
            }
        },
        "requests.NextPerformanceRequest": {
            "type": "object",
            "required": [
                "description",
                "performer",
                "starts_at",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "performer": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "requests.PerformanceRequest": {
            "type": "object",
            "required": [
                "performer",
                "title"
            ],
            "properties": {
                "performer": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.MusicResponse": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "should_be_muted": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "responses.PerformancesResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string"
                },
                "musics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.MusicResponse"
                    }
                },
                "performer": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "responses.Result": {
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "responses.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Result"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ultradonguri API",
	Description:      "Sohosai 2025 project telop sending API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
