name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image tag from branch name
        id: tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tag=production" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "tag=develop" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./prod.Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/sohosai/${{ github.event.repository.name }}:${{ steps.tag.outputs.tag }}
            ghcr.io/sohosai/${{ github.event.repository.name }}:latest
